
default: all

CC = gcc

CONFIG += ansi
CONFIG += debug

CxPath = ../cx
BinPath = ../bin
BldPath = eva

ExeList = eva pipelisp
ExeList := $(addprefix $(BinPath)/,$(ExeList))
Objs = $(addprefix $(BldPath)/,$(addsuffix .o,$(Deps)) sxpn.o)

include $(CxPath)/include.mk

all: $(ExeList)

$(BldPath)/sxpn.o: $(BldPath)/sxpn.c $(BldPath)/sxpn.h
$(BldPath)/eva.o: $(BldPath)/sxpn.h

$(call binexe,eva): $(BldPath)/eva.o \
	$(BldPath)/sxpn.o \
	$(addprefix $(CxBldPath)/,alphatab.o fileb.o syscx.o rbtree.o bstree.o)
	$(CC) $(CFLAGS) -o $@ $^

$(call binexe,pipelisp): $(BldPath)/pipelisp.o \
	$(addprefix $(CxBldPath)/,alphatab.o fileb.o syscx.o)
	$(CC) $(CFLAGS) -o $@ $^

.PHONY: clean
clean:
	rm -fr $(PfxBldPath)
	rm -f $(ExeList)

